f{% if 'centos' in version %}
FROM centos:7

RUN \
  rpm -i http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm && \
  yum -y install marathon mesos
{% elif 'ubuntu' in version %}
FROM ubuntu:15.04

RUN \
  apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF && \
  echo deb http://repos.mesosphere.com/ubuntu trusty main > /etc/apt/sources.list.d/mesosphere.list && \
  apt-get update && \
  apt-get -y install marathon mesos curl
{% endif %}

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
